import React, { useState } from 'react';
import { Card, CardContent, CardHeader } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Clock, MapPin, User, Sparkles, Zap, CheckCircle2, RefreshCw } from 'lucide-react';

interface ClassSchedule {
  subject: string;
  code: string;
  faculty: string;
  room: string;
  time: string;
  type: 'Lecture' | 'Lab' | 'Tutorial';
}

const INITIAL_TIMETABLE: Record<string, ClassSchedule[]> = {
  Monday: [
    { subject: 'Data Structures and Algorithms', code: 'CS301', faculty: 'Dr. Arindam Sen', room: 'LHC-101', time: '09:00 AM - 10:30 AM', type: 'Lecture' },
    { subject: 'Database Management Systems', code: 'CS302', faculty: 'Prof. Rajesh K. Mehta', room: 'LHC-102', time: '11:00 AM - 12:30 PM', type: 'Lecture' },
    { subject: 'Digital Communications Lab', code: 'EC308', faculty: 'Prof. Meera Deshmukh', room: 'Lab Block-4', time: '01:30 PM - 03:30 PM', type: 'Lab' },
  ],
  Tuesday: [
    { subject: 'Theory of Computation', code: 'CS303', faculty: 'Dr. Vikrant Singh', room: 'LHC-201', time: '09:00 AM - 10:30 AM', type: 'Lecture' },
    { subject: 'Data Structures Lab', code: 'CS307', faculty: 'Dr. Arindam Sen', room: 'Computing Lab-2', time: '11:00 AM - 01:00 PM', type: 'Lab' },
    { subject: 'Technical Writing', code: 'HU301', faculty: 'Prof. Sarah Thomas', room: 'LHC-103', time: '02:00 PM - 03:30 PM', type: 'Tutorial' },
  ],
  Wednesday: [
    { subject: 'Data Structures and Algorithms', code: 'CS301', faculty: 'Dr. Arindam Sen', room: 'LHC-101', time: '09:00 AM - 10:30 AM', type: 'Lecture' },
    { subject: 'Database Management Systems', code: 'CS302', faculty: 'Prof. Rajesh K. Mehta', room: 'LHC-102', time: '11:00 AM - 12:30 PM', type: 'Lecture' },
    { subject: 'Machine Learning', code: 'AI401', faculty: 'Dr. Amit Patel', room: 'LHC-204', time: '02:00 PM - 03:30 PM', type: 'Lecture' },
  ],
  Thursday: [
    { subject: 'Theory of Computation', code: 'CS303', faculty: 'Dr. Vikrant Singh', room: 'LHC-201', time: '09:00 AM - 10:30 AM', type: 'Lecture' },
    { subject: 'Analog & Digital Electronics', code: 'EC301', faculty: 'Prof. Meera Deshmukh', room: 'LHC-104', time: '11:00 AM - 12:30 PM', type: 'Lecture' },
    { subject: 'Academic Mentoring Class', code: 'ME001', faculty: 'Dr. Vikram Rathore', room: 'LHC-101', time: '01:30 PM - 03:00 PM', type: 'Tutorial' },
  ],
  Friday: [
    { subject: 'Analog & Digital Electronics', code: 'EC301', faculty: 'Prof. Meera Deshmukh', room: 'LHC-104', time: '09:00 AM - 10:30 AM', type: 'Lecture' },
    { subject: 'Database Systems Lab', code: 'CS308', faculty: 'Prof. Rajesh K. Mehta', room: 'Database Lab', time: '11:00 AM - 01:00 PM', type: 'Lab' },
    { subject: 'Guest Lecture Series', code: 'GL001', faculty: 'External Experts', room: 'Auditorium', time: '02:00 PM - 04:00 PM', type: 'Lecture' },
  ],
};

export const Timetable: React.FC = () => {
  const [timetable, setTimetable] = useState(INITIAL_TIMETABLE);
  const [isGenerating, setIsGenerating] = useState(false);
  const [showModal, setShowModal] = useState(false);

  const handleAIGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setShowModal(false);
      // Optimized clash-free timetable generated by AI algorithm
      setTimetable({
        Monday: [
          { subject: 'Machine Learning (AI Specialization)', code: 'AI401', faculty: 'Dr. Amit Patel', room: 'Quantum Lab 1', time: '09:00 AM - 10:30 AM', type: 'Lecture' },
          { subject: 'Data Structures and Algorithms', code: 'CS301', faculty: 'Dr. Arindam Sen', room: 'LHC-101', time: '11:00 AM - 12:30 PM', type: 'Lecture' },
          { subject: 'AI & Robotics Practical', code: 'AI405', faculty: 'Dr. Sarah Jenkins', room: 'Robotics Wing B', time: '01:30 PM - 03:30 PM', type: 'Lab' },
        ],
        Tuesday: [
          { subject: 'Database Management Systems', code: 'CS302', faculty: 'Prof. Rajesh K. Mehta', room: 'LHC-102', time: '09:00 AM - 10:30 AM', type: 'Lecture' },
          { subject: 'High Performance Computing', code: 'CS402', faculty: 'Dr. Vikrant Singh', room: 'Server Room 2', time: '11:00 AM - 01:00 PM', type: 'Lab' },
          { subject: 'Technical Writing & Ethics', code: 'HU301', faculty: 'Prof. Sarah Thomas', room: 'LHC-103', time: '02:00 PM - 03:30 PM', type: 'Tutorial' },
        ],
        Wednesday: [
          { subject: 'Distributed Systems', code: 'CS404', faculty: 'Dr. Arindam Sen', room: 'LHC-101', time: '09:00 AM - 10:30 AM', type: 'Lecture' },
          { subject: 'Cloud Infrastructure Lab', code: 'CS408', faculty: 'Prof. Rajesh K. Mehta', room: 'Cloud Hub 3', time: '11:00 AM - 01:00 PM', type: 'Lab' },
        ],
        Thursday: timetable.Thursday,
        Friday: timetable.Friday,
      });
    }, 1800);
  };

  return (
    <div className="flex flex-col gap-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-slate-900 dark:text-slate-100 font-display m-0 leading-tight flex items-center gap-2">
            Timetable & Schedules
            <span className="text-xs px-2.5 py-0.5 rounded-full bg-blue-500/20 text-blue-400 border border-blue-500/30">
              AI Optimized
            </span>
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            View weekly schedules, class assignments, teaching faculty, and classroom locations.
          </p>
        </div>

        <button
          onClick={() => setShowModal(true)}
          className="px-4 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white rounded-xl text-xs font-semibold flex items-center gap-2 shadow-lg shadow-blue-500/20 transition-all self-start"
        >
          <Sparkles size={16} />
          Generate AI Timetable
        </button>
      </div>

      {/* Week Timeline layout */}
      <div className="flex flex-col gap-6">
        {Object.entries(timetable).map(([day, slots]) => (
          <div key={day} className="grid grid-cols-1 lg:grid-cols-12 gap-4 items-start">
            {/* Left Day Badge */}
            <div className="lg:col-span-2 pt-2">
              <h3 className="text-xs font-bold font-display uppercase tracking-wider text-slate-800 dark:text-slate-300">
                {day}
              </h3>
              <span className="text-[10px] text-slate-400 font-medium">
                {slots.length} Classes scheduled
              </span>
            </div>

            {/* Slots timeline */}
            <div className="lg:col-span-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3.5">
              {slots.map((slot, idx) => (
                <Card key={idx} hoverable className="border border-slate-150 dark:border-slate-800/80">
                  <CardHeader className="p-4 flex items-center justify-between border-none">
                    <div className="flex items-center gap-1.5">
                      <span className="text-[10px] font-mono font-bold text-blue-600 dark:text-blue-400">
                        {slot.code}
                      </span>
                      <span className="text-slate-300">•</span>
                      <Badge
                        variant={
                          slot.type === 'Lecture'
                            ? 'primary'
                            : slot.type === 'Lab'
                            ? 'success'
                            : 'warning'
                        }
                        className="text-[8px] py-0 px-1.5"
                      >
                        {slot.type}
                      </Badge>
                    </div>
                  </CardHeader>
                  <CardContent className="px-4 pb-4 pt-0 flex flex-col gap-3">
                    <h4 className="text-xs font-bold text-slate-900 dark:text-slate-150 leading-snug">
                      {slot.subject}
                    </h4>

                    <div className="flex flex-col gap-1 text-[11px] text-slate-500 dark:text-slate-400">
                      <div className="flex items-center gap-1.5">
                        <Clock size={12} className="text-slate-400 shrink-0" />
                        <span>{slot.time}</span>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <User size={12} className="text-slate-400 shrink-0" />
                        <span>{slot.faculty}</span>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <MapPin size={12} className="text-slate-400 shrink-0" />
                        <span className="font-semibold text-slate-600 dark:text-slate-300">{slot.room}</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* AI Timetable Generator Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-md p-4">
          <div className="glass-card w-full max-w-lg p-6 space-y-4 border border-blue-500/30">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-blue-600 text-white">
                <Sparkles size={22} className="animate-spin" />
              </div>
              <div>
                <h3 className="text-base font-bold text-slate-100">AI Timetable Generator v2.0</h3>
                <p className="text-xs text-slate-400">Constraint Solver for Faculty, Labs, Rooms & Capacity</p>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-2 text-xs text-slate-300">
              <h4 className="font-bold text-blue-400">Optimization Inputs:</h4>
              <ul className="list-disc pl-4 space-y-1 text-slate-400">
                <li>Faculty Availability Matrices (Zero Overlaps)</li>
                <li>Lab Equipment & Seating Capacity Limits</li>
                <li>Room Allocation & Distance Optimization between LHC blocks</li>
                <li>Student Credit Loads & Break Intervals</li>
              </ul>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                onClick={() => setShowModal(false)}
                className="px-4 py-2 bg-slate-800 text-slate-300 text-xs rounded-xl"
              >
                Cancel
              </button>
              <button
                onClick={handleAIGenerate}
                disabled={isGenerating}
                className="px-5 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-bold text-xs rounded-xl shadow-lg shadow-blue-500/20 flex items-center gap-2"
              >
                {isGenerating ? <RefreshCw size={14} className="animate-spin" /> : <Zap size={14} />}
                {isGenerating ? 'Running Constraint Solver...' : 'Generate Optimized Timetable'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
