export interface PredictiveInsight {
  id: string;
  category: 'Attendance' | 'ExamClash' | 'Weather' | 'AcademicRisk';
  targetGroup: string; // e.g. "CSE-2A", "ECE-3B", "ME-201"
  observation: string; // Gemini says: Attendance in CSE-2A is dropping.
  reason: string;      // Reason: Monday first lecture attendance decreases after festivals.
  suggestion: string;  // Suggestion: Move lab timing to 11:15 AM.
  confidenceScore: number; // e.g. 92%
  projectedImpact: string; // e.g. +14% Attendance Gain
  actionTitle: string;
  actionPayload: string;
}

export class PredictiveAnalyticsEngine {
  /**
   * Returns all active predictive insights generated by Gemini AI
   */
  static getPredictiveInsights(): PredictiveInsight[] {
    return [
      {
        id: 'pred-1',
        category: 'Attendance',
        targetGroup: 'CSE-2A (Semester 4)',
        observation: 'Attendance in CSE-2A Monday first lecture is dropping (-14.2%).',
        reason: 'Historical telemetry shows Monday 8:30 AM first lecture attendance consistently decreases by 28% after major festivals & long weekends due to return transit delays.',
        suggestion: 'Move Monday 8:30 AM Lab timing to 11:15 AM on post-festival weeks, or convert to hybrid telemetry submission.',
        confidenceScore: 92,
        projectedImpact: '+14.2% Attendance Recovery',
        actionTitle: 'Reschedule Monday 8:30 AM Lab to 11:15 AM',
        actionPayload: 'RESCHEDULE_CSE2A_POST_FESTIVAL_LAB',
      },
      {
        id: 'pred-2',
        category: 'ExamClash',
        targetGroup: 'ECE-3B (Semester 6)',
        observation: 'ECE-3B Data Structures lecture attendance dropping 12% in Week 6.',
        reason: 'Students prioritize back-to-back Mid-Semester Lab evaluations scheduled on Tuesdays over Monday theoretical lectures.',
        suggestion: 'Stagger lab assignment deadlines by 48 hours to eliminate evaluation clash and reduce student burnout.',
        confidenceScore: 89,
        projectedImpact: '+10.5% Lecture Engagement',
        actionTitle: 'Stagger Lab Assignment Deadlines by 48 Hours',
        actionPayload: 'STAGGER_ECE3B_LAB_DEADLINES',
      },
      {
        id: 'pred-3',
        category: 'Weather',
        targetGroup: 'Commuter Students (Routes 2 & 4)',
        observation: 'Predictive 8.4% morning attendance shortage expected next week.',
        reason: 'Weather telemetry predicts heavy monsoon rainfall; Bus Routes 2 & 4 historical GPS shows 25-minute transit delays.',
        suggestion: 'Activate hybrid online lecture streams for 8:00 AM theory classes on heavy rain alert days.',
        confidenceScore: 94,
        projectedImpact: 'Zero Loss of Academic Hours',
        actionTitle: 'Enable Hybrid Rain Stream for 8 AM Classes',
        actionPayload: 'ENABLE_HYBRID_RAIN_STREAM',
      },
      {
        id: 'pred-4',
        category: 'AcademicRisk',
        targetGroup: 'ME-201 Thermodynamics (14 Students)',
        observation: '14 students in ME-201 Thermodynamics flagged at 84% failure risk.',
        reason: 'Quiz 1 score < 40% combined with 3 consecutive missed tutorial sessions indicates early academic distress.',
        suggestion: 'Assign mandatory peer-tutoring sessions and dispatch early intervention alerts to academic advisors.',
        confidenceScore: 95,
        projectedImpact: '-68% Failure Probability',
        actionTitle: 'Assign Peer Tutoring & Alert Advisor',
        actionPayload: 'ASSIGN_ME201_PEER_TUTORING',
      },
    ];
  }

  /**
   * Execute 1-click predictive action
   */
  static executePredictiveAction(actionPayload: string): { success: boolean; message: string } {
    switch (actionPayload) {
      case 'RESCHEDULE_CSE2A_POST_FESTIVAL_LAB':
        return {
          success: true,
          message: 'AI Timetable Reschedule Applied: CSE-2A Monday 8:30 AM Lab moved to 11:15 AM for post-festival week. Notifications sent to 54 enrolled students.',
        };
      case 'STAGGER_ECE3B_LAB_DEADLINES':
        return {
          success: true,
          message: 'Deadline Extension Dispatched: ECE-3B Data Structures Lab submission extended by 48 hours to resolve Tuesday exam clash.',
        };
      case 'ENABLE_HYBRID_RAIN_STREAM':
        return {
          success: true,
          message: 'Hybrid Stream Ready: Auto-enabled live streaming for 8:00 AM theory classes on heavy rain alert days.',
        };
      case 'ASSIGN_ME201_PEER_TUTORING':
        return {
          success: true,
          message: 'Intervention Dispatched: Assigned CSE Senior Peer Tutors to 14 flagged ME-201 students and notified Dr. Arindam Sen.',
        };
      default:
        return {
          success: true,
          message: `Executed predictive action: ${actionPayload}`,
        };
    }
  }
}
